name: _dummy_screenshot_pkg
description: A dummy package published for testing purposes.
version: 1.4.2

environment:
  sdk: '>=2.16.1 <3.0.0'

dev_dependencies:
  lints: ^1.0.0

screenshots:
  - description: 'pub package picture'
    path: pub_package.png
  - description: 'this is an awesome screenshot.'
    path: static.webp
  - description: 'sun is shining'
    path: sun.png
  - description: 'video player gif'
    path: demo_ipod.webp
  - description: 'a very wide image'
    path: horizontal.png
  - description: 'a very tall image'
    path: vertical.png
