name: _dummy_screenshot_pkg
description: A dummy package published for testing purposes.
version: 1.2.0

environment:
  sdk: '>=2.16.1 <3.0.0'

dev_dependencies:
  lints: ^1.0.0

screenshots:
  - description: 'this is an awesome screenshot.'
    path: static.webp
  - description: 'pub package picture'
    path: pub_package.png
  - description: 'sun is shining'
    path: sun.png
