# Created with https://github.com/dart-lang/mono_repo
language: dart

dart:
  - dev
  - stable

env:
  - PKG=app TASK=dartanalyzer
  - PKG=app TASK=dartfmt
  - PKG=app TASK=test

matrix:
  allow_failures:
    - dart: dev
      env: PKG=app TASK=dartfmt

script: ./tool/travis.sh

# Only building master means that we don't run two builds for each pull request.
branches:
  only: [master]

cache:
 directories:
   - $HOME/.pub-cache
