# Configuration for production deployment.
# This will use the Datastore from the cloud project and the Cloud Storage
# bucket 'pub-packages'. The credentials for accessing the Cloud
# Storage is retrieved from the Datastore.
---
canonicalPackagesBucketName: dartlang-pub-canonical-packages
publicPackagesBucketName: dartlang-pub-public-packages
incomingPackagesBucketName: dartlang-pub-incoming-packages
projectId: dartlang-pub
searchServicePrefix: https://search-dot-dartlang-pub.appspot.com
defaultServiceBaseUrl: https://{{GAE_VERSION}}-dot-{{GOOGLE_CLOUD_PROJECT}}.appspot.com
dartdocStorageBucketName: dartlang-pub--dartdoc-storage
popularityDumpBucketName: dartlang-pub--popularity
searchSnapshotBucketName: dartlang-pub--search-snapshot
maxTaskInstances: 700
maxTaskRunHours: 2
taskResultBucketName: dartlang-pub-task-output
taskWorkerImage: us-central1-docker.pkg.dev/dartlang-pub-tasks/{{GOOGLE_CLOUD_PROJECT}}-worker-images/task-worker:{{GAE_VERSION}}
taskWorkerProject: dartlang-pub-tasks
taskWorkerNetwork: pub-workers
cosImage: projects/cos-cloud/global/images/family/cos-97-lts
taskWorkerServiceAccount: task-worker@dartlang-pub-tasks.iam.gserviceaccount.com
imageBucketName: dartlang-pub--pub-images
storageBaseUrl: https://storage.googleapis.com
pubClientAudience: 818368855108-8grd2eg9tj9f38os6f1urbcvsq399u8n.apps.googleusercontent.com
pubSiteAudience: 818368855108-e8skaopm5ih5nbb82vhh66k7ft5o7dn3.apps.googleusercontent.com
pubServerAudience: 818368855108-ulq5tn5t51ga21hg8jkcavbooaljiasp.apps.googleusercontent.com
externalServiceAudience: https://pub.dev
gmailRelayServiceAccount: pub-gsuite-gmail-delegatee@dartlang-pub.iam.gserviceaccount.com
gmailRelayImpersonatedGSuiteUser: noreply@pub.dev
uploadSignerServiceAccount: package-uploader-signer@dartlang-pub.iam.gserviceaccount.com
blockRobots: false
productionHosts:
- pub.dartlang.org
- pub.dev
- api.pub.dev
primaryApiUri: https://pub.dartlang.org/
primarySiteUri: https://pub.dev/
admins:
- oauthUserId: '106306194842560376600'
  email: assigned-tags-admin@dartlang-pub.iam.gserviceaccount.com
  permissions:
  - manageAssignedTags
- oauthUserId: '114536496314409930448'
  email: pub-admin-service@dartlang-pub.iam.gserviceaccount.com
  permissions:
  - listUsers
  - managePackageOwnership
  - removeUsers
- oauthUserId: '108693445730271975989'
  email: pub-moderation-admin@dartlang-pub.iam.gserviceaccount.com
  permissions:
  - executeTool
  - listUsers
  - manageAssignedTags
  - managePackageOwnership
  - manageRetraction
  - removePackage
  - removeUsers
tools:
  # Needs to be in sync with Dockerfile, setup-dart.sh and setup-flutter.sh
  stableDartSdkPath: '/tool/stable/dart-sdk'
  stableFlutterSdkPath: '/tool/stable/flutter'
  previewDartSdkPath: '/tool/preview/dart-sdk'
  previewFlutterSdkPath: '/tool/preview/flutter'
  futureDartSdkPath: '/tool/preview/dart-sdk' # same as preview
  futureFlutterSdkPath: '/tool/future/flutter'
