# dev config
projectId: dartlang-pub-dev
packageBucketName: dartlang-pub-dev--pub-packages
dartdocStorageBucketName: 'dartlang-pub-dev--dartdoc-storage'
popularityDumpBucketName: 'dartlang-pub-dev--popularity'
searchSnapshotBucketName: 'dartlang-pub-dev--search-snapshot'
backupSnapshotBucketName: 'dartlang-pub-dev--backup-snapshots'
# TODO: Support finding search on localhost when envConfig.isRunningLocally
#      is true this also requires running search on localhost.
searchServicePrefix: 'https://search-dot-dartlang-pub-dev.appspot.com'
storageBaseUrl: 'https://storage.googleapis.com/'
pubClientAudience: _pubClientAudience
pubSiteAudience: '621485135717-idb8t8nnguphtu2drfn2u4ig7r56rm6n.apps.googleusercontent.com'
adminAudience: 'https://pub.dev'
gmailRelayServiceAccount:  # disable email sending
gmailRelayImpersonatedGSuiteUser:  # disable email sending
uploadSignerServiceAccount: 'package-uploader-signer@dartlang-pub-dev.iam.gserviceaccount.com'
blockRobots: true
productionHosts:
- localhost
primaryApiUri: https://dartlang-pub-dev.appspot.com
primarySiteUri: http://localhost:8080
admins:
- oauthUserId: '111042304059633250784'
  email: 'istvan.soos@gmail.com'
  permissions:
  - listUsers
  - removeUsers
  - manageAssignedTags
  - removePackage
- oauthUserId: '117672289743137340098'
  email: 'assigned-tags-admin@dartlang-pub-dev.iam.gserviceaccount.com'
  permissions:
  - manageAssignedTags
