# Configuration for production deployment.
# This will use the Datastore from the cloud project and the Cloud Storage
# bucket 'pub-packages'. The credentials for accessing the Cloud
# Storage is retrieved from the Datastore.
---
packageBucketName: pub-packages
projectId: dartlang-pub
searchServicePrefix: https://search-dot-dartlang-pub.appspot.com
dartdocStorageBucketName: dartlang-pub--dartdoc-storage
popularityDumpBucketName: dartlang-pub--popularity
searchSnapshotBucketName: dartlang-pub--search-snapshot
storageBaseUrl: https://storage.googleapis.com/
pubClientAudience: 818368855108-8grd2eg9tj9f38os6f1urbcvsq399u8n.apps.googleusercontent.com
pubSiteAudience: 818368855108-e8skaopm5ih5nbb82vhh66k7ft5o7dn3.apps.googleusercontent.com
adminAudience: https://pub.dev
gmailRelayServiceAccount: pub-gsuite-gmail-delegatee@dartlang-pub.iam.gserviceaccount.com
gmailRelayImpersonatedGSuiteUser: noreply@pub.dev
uploadSignerServiceAccount: package-uploader-signer@dartlang-pub.iam.gserviceaccount.com
blockRobots: false
productionHosts:
- pub.dartlang.org
- pub.dev
- api.pub.dev
primaryApiUri: https://pub.dartlang.org/
primarySiteUri: https://pub.dev/
admins:
- oauthUserId: '106306194842560376600'
  email: assigned-tags-admin@dartlang-pub.iam.gserviceaccount.com
  permissions:
  - manageAssignedTags
- oauthUserId: '114536496314409930448'
  email: pub-admin-service@dartlang-pub.iam.gserviceaccount.com
  permissions:
  - listUsers
  - removeUsers
  - managePackageUploaders
- oauthUserId: '108693445730271975989'
  email: pub-moderation-admin@dartlang-pub.iam.gserviceaccount.com
  permissions:
  - removePackage
