projectId: dartlang-pub-dev
packageBucketName: dartlang-pub-dev--pub-packages
dartdocStorageBucketName: 'dartlang-pub-dev--dartdoc-storage'
popularityDumpBucketName: 'dartlang-pub-dev--popularity'
searchSnapshotBucketName: 'dartlang-pub-dev--search-snapshot'
backupSnapshotBucketName: 'dartlang-pub-dev--backup-snapshots'
searchServicePrefix: 'https://search-dot-dartlang-pub-dev.appspot.com'
storageBaseUrl: 'https://storage.googleapis.com/'
pubClientAudience: '818368855108-8grd2eg9tj9f38os6f1urbcvsq399u8n.apps.googleusercontent.com'
pubSiteAudience: '621485135717-idb8t8nnguphtu2drfn2u4ig7r56rm6n.apps.googleusercontent.com'
adminAudience: 'https://pub.dev'
gmailRelayServiceAccount:
gmailRelayImpersonatedGSuiteUser:
uploadSignerServiceAccount: 'package-uploader-signer@dartlang-pub-dev.iam.gserviceaccount.com'
blockRobots: true
productionHosts:
- dartlang-pub-dev.appspot.com
- dartlang-pub-dev-dot-dartlang-pub-dev.appspot.com
primaryApiUri: https://dartlang-pub-dev.appspot.com
primarySiteUri: https://dartlang-pub-dev-dot-dartlang-pub-dev.appspot.com

admins:
- oauthUserId: '111042304059633250784'
  email: 'istvan.soos@gmail.com'
  permissions:
  - listUsers
  - removeUsers
  - manageAssignedTags
  - removePackage
- oauthUserId: '117672289743137340098'
  email: 'assigned-tags-admin@dartlang-pub-dev.iam.gserviceaccount.com'
  permissions:
  - listUsers
  - removeUsers
  - manageAssignedTags
  - removePackage
