---
packageBucketName: dartlang-pub-dev--pub-packages
projectId: dartlang-pub-dev
searchServicePrefix: https://search-dot-dartlang-pub-dev.appspot.com
dartdocStorageBucketName: dartlang-pub-dev--dartdoc-storage
popularityDumpBucketName: dartlang-pub-dev--popularity
searchSnapshotBucketName: dartlang-pub-dev--search-snapshot
imageBucketName: dartlang-pub-dev--pub-images
storageBaseUrl: https://storage.googleapis.com/
pubClientAudience: 818368855108-8grd2eg9tj9f38os6f1urbcvsq399u8n.apps.googleusercontent.com
pubSiteAudience: 621485135717-idb8t8nnguphtu2drfn2u4ig7r56rm6n.apps.googleusercontent.com
adminAudience: https://pub.dev
gmailRelayServiceAccount:
gmailRelayImpersonatedGSuiteUser:
uploadSignerServiceAccount: package-uploader-signer@dartlang-pub-dev.iam.gserviceaccount.com
blockRobots: true
productionHosts:
- localhost
primaryApiUri: https://dartlang-pub-dev.appspot.com
primarySiteUri: http://localhost:8080
admins:
- oauthUserId: '111042304059633250784'
  email: istvan.soos@gmail.com
  permissions:
  - listUsers
  - manageAssignedTags
  - managePackageOwnership
  - manageRetraction
  - removePackage
  - removeUsers
- oauthUserId: '117672289743137340098'
  email: assigned-tags-admin@dartlang-pub-dev.iam.gserviceaccount.com
  permissions:
  - manageAssignedTags
