# See https://github.com/dart-lang/mono_repo for details
dart:
  - 2.13.3

stages:
  - smoke_test:
    - group:
        - dartfmt
        - dartanalyzer: --fatal-infos  .
  - unit_test:
    - test: --run-skipped
