name: _popularity
publish_to: none

environment:
  sdk: '>=2.14.0 <3.0.0'

dependencies:
  json_annotation: ^4.3.0

dev_dependencies:
  build_runner: ^2.0.0
  build_verify: ^2.0.0
  json_serializable: ^6.0.1
  test: ^1.3.0
