name: _popularity
description: Not to be published

environment:
  sdk: '>=1.20.1 <3.0.0'

dependencies:
  json_annotation: ^0.2.0

dev_dependencies:
  build_runner: ^0.9.1
  json_serializable: ^0.5.0
  test: ^1.3.0
