name: _popularity
description: Not to be published

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  json_annotation: ^1.1.0

dev_dependencies:
  build_runner: ^0.10.0
  json_serializable: ^1.1.0
  test: ^1.3.0
