name: _popularity
description: Not to be published

environment:
  sdk: '>=1.20.1 <2.0.0'

dependencies:
  json_annotation: ^0.2.0

dev_dependencies:
  build_runner: ^0.8.10
  json_serializable: ^0.5.0
  test: ^0.12.0
