name: _popularity
publish_to: none

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  json_annotation: '>=3.0.0 <5.0.0'

dev_dependencies:
  build_runner: ^2.0.0
  build_verify: ^2.0.0
  json_serializable: ^4.0.0
  test: ^1.3.0
