# See https://github.com/dart-lang/mono_repo for details
dart:
  - 2.1.0-dev.9.4

stages:
  - smoke_test:
    - group:
        - dartfmt
        - dartanalyzer: --fatal-infos --fatal-warnings .
  - unit_test:
    - test: --run-skipped
