# See https://pub.dev/packages/mono_repo for details on this file
sdk:
  - 3.2.0

stages:
  - smoke_test:
    - group:
        - format
        # dart analyze doesn't support multiple dirs. A bug?
        - analyze: --fatal-infos lib/
        - analyze: --fatal-infos test/
  - unit_test:
      - test: --run-skipped --total-shards 3 --shard-index 0
      - test: --run-skipped --total-shards 3 --shard-index 1
      - test: --run-skipped --total-shards 3 --shard-index 2
