# See https://github.com/dart-lang/mono_repo for details
dart:
  - 2.8.1

stages:
  - smoke_test:
    - group:
        - dartfmt
        - dartanalyzer: --fatal-infos --fatal-warnings bin/ lib/
  - unit_test:
    - test: --run-skipped --concurrency=1
