# See https://pub.dev/packages/mono_repo for details on this file
dart:
  - 2.13.3

stages:
  - smoke_test:
    - group:
        - format
        # dart analyze doesn't support multiple dirs. A bug?
        - analyze: --fatal-infos bin/
        - analyze: --fatal-infos lib/
  - unit_test:
      - test: --run-skipped --concurrency=1 `find test -name "*_test\\.dart" | sort | sed -n '0~3p'`
      - test: --run-skipped --concurrency=1 `find test -name "*_test\\.dart" | sort | sed -n '1~3p'`
      - test: --run-skipped --concurrency=1 `find test -name "*_test\\.dart" | sort | sed -n '2~3p'`
