name: pub_integration
publish_to: none  # don't publish yet
description: Tools for integration tests.

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  _pub_shared:
    path: ../_pub_shared
  args: ^2.0.0
  http: ^0.13.0
  path: ^1.8.0
  pub_semver: ^2.0.0
  puppeteer: ^2.12.0
  oauth2: ^2.0.0

dev_dependencies:
  coverage: any # test already depends on it
  test: ^1.16.5
