name: pub_integration
publish_to: none  # don't publish yet
description: Tools for integration tests.

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  args: ^2.0.0
  http: ^0.13.0
  path: ^1.8.0
  pub_semver: ^2.0.0
  pub_validations:
    path: ../pub_validations
  puppeteer: 2.0.0

dev_dependencies:
  coverage: any # test already depends on it
  test: ^1.16.5
