name: pub_integration
publish_to: none  # don't publish yet
description: Tools for integration tests.

environment:
  sdk: '>=2.3.0 <3.0.0'

dependencies:
  args: ^1.5.0
  http: ^0.12.0
  meta: ^1.0.0
  path: ^1.0.0
  pub_semver: ^1.4.2

dev_dependencies:
  test: ^1.6.3
