# Read about `build.yaml` at https://pub.dartlang.org/packages/build_config
# To update generated code, run `pub run build_runner build`
targets:
  pub_dartlang_org:
    sources:
      - 'lib/history/models.dart'
      - 'lib/dartdoc/models.dart'
      - 'lib/frontend/handlers/routes.dart'
      - 'lib/frontend/handlers/redirects.dart'
      - 'lib/scorecard/models.dart'
      - 'lib/shared/*.dart'
      - 'lib/search/backend*.dart'
      - 'lib/frontend/handlers/pubapi.dart'
