# See https://github.com/dart-lang/mono_repo for details
sdk:
  - 2.16.1

stages:
  - smoke_test:
    - group:
        - format
        - analyze: --fatal-infos  .
  - unit_test:
    - test: --run-skipped --total-shards 7 --shard-index 0
    - test: --run-skipped --total-shards 7 --shard-index 1
    - test: --run-skipped --total-shards 7 --shard-index 2
    - test: --run-skipped --total-shards 7 --shard-index 3
    - test: --run-skipped --total-shards 7 --shard-index 4
    - test: --run-skipped --total-shards 7 --shard-index 5
    - test: --run-skipped --total-shards 7 --shard-index 6

cache:
  directories:
    - ".dart_tool/pub-test-profile"
    - ".dart_tool/pub-search-data"
