# See https://github.com/dart-lang/mono_repo for details
dart:
  - 2.14.1

stages:
  - smoke_test:
    - group:
        - format
        - analyze: --fatal-infos  .
  - unit_test:
    - test: --run-skipped `find test -name "*_test\\.dart" | sort | sed -n '0~7p'`
    - test: --run-skipped `find test -name "*_test\\.dart" | sort | sed -n '1~7p'`
    - test: --run-skipped `find test -name "*_test\\.dart" | sort | sed -n '2~7p'`
    - test: --run-skipped `find test -name "*_test\\.dart" | sort | sed -n '3~7p'`
    - test: --run-skipped `find test -name "*_test\\.dart" | sort | sed -n '4~7p'`
    - test: --run-skipped `find test -name "*_test\\.dart" | sort | sed -n '5~7p'`
    - test: --run-skipped `find test -name "*_test\\.dart" | sort | sed -n '6~7p'`

cache:
  directories:
    - ".dart_tool/pub-test-profile"
    - ".dart_tool/pub-search-data"
