name: pub_dartlang_org
version: 0.1.0
author: Dart Team
description: The pub.dartlang.org website.
sdk: ">=1.19.0 <2.0.0"
dependencies:
  appengine: '^0.4.1'
  args: '^0.13.7'
  gcloud: '>=0.4.0 <0.5.0'
  googleapis: '>=0.31.0 <0.37.0'
  googleapis_auth: '>=0.2.2 <0.2.4'
  html: '>=0.12.0 <0.14.0'
  http: '>=0.11.0 <0.12.0'
  intl: '>=0.13.0 <0.16.0'
  logging: '>=0.9.3 <1.0.0'
  markdown: '>=0.11.0 <0.12.0'
  mime: '>=0.9.3 <0.10.0'
  mustache: '>=0.2.3 <0.3.0'
  pub_semver: ">=1.2.2 <2.0.0"
  pub_server: ">=0.1.0 <0.2.0"
  shelf: '>=0.5.6 <0.7.0'
  stream_transform: ^0.0.7
  # pana version to be pinned
  # keep in-sync with app/lib/analyzer/versions.dart
  pana: '0.3.0'
  # 3rd-party packages with pinned versions
  archive: '1.0.31'
  uuid: '0.5.3'

dev_dependencies:
  test: ">=0.12.20 <0.13.0"
