name: pub_dartlang_org
author: Dart Team <misc@dartlang.org>
description: The pub.dartlang.org website.
environment:
  sdk: ">=1.25.0-dev.9.0 <2.0.0"
dependencies:
  _popularity:
    path: ../pkg/_popularity
  appengine: '^0.4.3'
  args: '>=0.13.7 <2.0.0'
  crypto: '^2.0.2'
  gcloud: '>=0.4.0 <0.5.0'
  googleapis: '>=0.31.0 <0.50.0'
  googleapis_auth: ^0.2.4
  html: '>=0.12.0 <0.14.0'
  http: '>=0.11.0 <0.12.0'
  http_parser: '>=3.1.1 <4.0.0'
  intl: '>=0.13.0 <0.16.0'
  json_annotation: '^0.2.0'
  logging: '>=0.9.3 <1.0.0'
  markdown: '>=1.1.0 <1.2.0'
  memcache: '^0.2.1+1'
  meta: ^1.1.2
  mime: '>=0.9.3 <0.10.0'
  mustache: ^1.0.0
  path: '^1.4.2'
  pub_semver: ">=1.2.2 <2.0.0"
  pub_server: ">=0.1.0 <0.2.0"
  shelf: '>=0.5.6 <0.8.0'
  stream_transform: ^0.0.7
  yaml: '^2.1.12'
  # pana version to be pinned
  # keep in-sync with app/lib/analyzer/versions.dart
  pana: '0.10.1'
  # 3rd-party packages with pinned versions
  archive: '1.0.33'
  uuid: '0.5.3'

dev_dependencies:
  build_runner: '^0.7.0'
  json_serializable: '^0.3.1'
  source_gen: '^0.7.2'
  test: ">=0.12.20 <0.13.0"

dependency_overrides:
  # Fixes https://github.com/dart-lang/pana/issues/138
  # Required until we have a 'gold' release
  analyzer: 0.31.1
