targets:
  $default:
    builders:
      shelf_router_generator|shelf_router:
        enabled: true

builders:
  api_router:
    import: "package:api_generator/builder.dart"
    builder_factories: ["apiRouter"]
    build_extensions: {".dart": [".api_router.g.part"]}
    auto_apply: dependents
    build_to: cache
    applies_builders: ["source_gen|combining_builder"]
