# See https://pub.dev/packages/mono_repo for details on this file
dart:
  - 2.12.0

stages:
  - smoke_test:
    - group:
        - dartfmt
        - dartanalyzer: --fatal-infos  .
  - build:
    - command: ./build.sh
  - unit_test:
    - test: --run-skipped
