# See https://github.com/dart-lang/mono_repo for details
dart:
  - 2.8.1

stages:
  - smoke_test:
    - group:
        - dartfmt
        - dartanalyzer: --fatal-infos --fatal-warnings .
  - build:
    - command: ./build.sh
  - unit_test:
    - test: --run-skipped
