name: web_app
publish_to: none

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  _pub_shared:
    path: ../_pub_shared
  api_builder:
    path: ../api_builder
  http: ^0.13.0
  js: ^0.6.1
  markdown: ^7.0.2
  mdc_web: ^0.6.0
  meta: ^1.3.0

dev_dependencies:
  test: ^1.16.5
