name: pub_dartdoc
author: Dart Team <misc@dartlang.org>
description: The customized dartdoc for pub.dartlang.org.
environment:
  sdk: ">=2.0.0 <2.2.0"
dependencies:
  json_annotation: '^1.1.0'
  logging: '>=0.9.3 <1.0.0'
  meta: ^1.1.5
  path: ^1.6.0
  # dartdoc version to be pinned
  dartdoc: 0.20.3

dev_dependencies:
  build_runner: '^0.10.0'
  json_serializable: '^1.1.0'
  source_gen: '^0.9.0'
  test: '^1.3.0'
