name: pub_dartdoc
description: The customized dartdoc for pub.dartlang.org.
environment:
  sdk: '^3.0.0'
dependencies:
  analyzer: any # whatever dartdoc supports
  path: ^1.8.0
  pub_dartdoc_data:
    path: ../pub_dartdoc_data
  # dartdoc version to be pinned, keep in-sync with app/lib/shared/versions.dart
  dartdoc: 7.0.0

dev_dependencies:
  coverage: any # test already depends on it
  http: ^1.0.0
  test: '^1.16.5'
  tar: ^1.0.0
