name: pub_validations
description: Shared validation for pub.dev
publish_to: none

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  html: ^0.15.0
  meta: ^1.3.0

dev_dependencies:
  test: ^1.16.5
