# Read about `build.yaml` at https://pub.dartlang.org/packages/build_config
# To update generated code, run `dart run build_runner build`
targets:
  $default:
    sources:
      - 'lib/pana_report.dart'
      - 'lib/src/testing/server.dart'
