name: pub_worker
description: Worker for pana and dartdoc analysis for pub.dev
publish_to: none

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  json_annotation: ^4.3.0
  jsontool: ^1.1.0
  pana: ^0.21.31
  meta: ^1.7.0
  api_builder:
    path: ../api_builder
  _pub_shared:
    path: ../_pub_shared
  http: ^0.13.4
  http_parser: ^4.0.0
  retry: ^3.1.0
  logging: ^1.0.2
  pub_dartdoc:
    path: ../pub_dartdoc
  indexed_blob:
    path: ../indexed_blob
  clock: ^1.1.0
  html: ^0.15.0
  pub_dartdoc_data:
    path: ../pub_dartdoc_data
  pubspec_parse: ^1.2.1
  tar: ^0.5.0
  shelf: ^1.2.0
  shelf_router: ^1.1.2
  async: ^2.10.0
  collection: ^1.17.0

dev_dependencies:
  test: ^1.19.3
  build_runner: ^2.1.5
  json_serializable: ^6.0.1
  shelf_router_generator: ^1.0.4
  args: ^2.3.1

