name: pub_worker
description: Worker for pana and dartdoc analysis for pub.dev
publish_to: none

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  json_annotation: ^4.3.0
  jsontool: ^1.1.0
  pana: ^0.21.20
  meta: ^1.7.0
  api_builder:
    path: ../api_builder
  _pub_shared:
    path: ../_pub_shared
  http: ^0.13.4
  http_parser: ^4.0.0
  retry: ^3.1.0
  logging: ^1.0.2
  indexed_blob:
    path: ../indexed_blob
  clock: ^1.1.0

dev_dependencies:
  tar: ^0.5.0
  test: ^1.19.3
  build_runner: ^2.1.5
  json_serializable: ^6.0.1
  shelf: ^1.2.0
  shelf_router: ^1.1.2
