# See https://github.com/dart-lang/mono_repo for details
sdk:
  - 2.16.1

stages:
  - smoke_test:
    - group:
        - format
        - analyze: --fatal-infos  .
  - unit_test:
    - test: --run-skipped
