# See https://pub.dev/packages/mono_repo for details on this file
dart:
  - 2.14.1

stages:
  - smoke_test:
      - group:
          - format
          - analyze: --fatal-infos .
  - unit_test:
      - test: --run-skipped
