name: simple_cache
description: A simple cache abstraction wrapping in-memory, redis, memcached.
publish_to: none # TODO: consider splitting this package into:
                 # simple_cache             // Cache wrapper
                 # simple_cache_provider    // CacheProvider interface + Inmemory
                 # simple_cache_redis       // CacheProvider implementation for redis
environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  convert: ^2.1.1
  logging: '^0.11.3'
  retry: ^3.0.0
  dartis: 0.3.0

dev_dependencies:
  test: ^1.5.1
