name: code_coverage
publish_to: none  # don't publish yet
description: Code coverage tools.
environment:
  sdk: '>=2.6.0 <3.0.0'

dependencies:
  args: ^1.5.0
  coverage: ^0.14.1
  lcov: ^6.0.0
  path: ^1.0.0
  source_maps: ^0.10.8

dev_dependencies:
  test: ^1.5.1
