name: _dummy_pkg
homepage: 'https://github.com/dart-lang/pub-dev'
description: 'Dummy packages published from pub integration tests.'
dependencies:
  retry: ^3.1.0
environment:
  sdk: ">=2.12.0 <4.0.0"
