name: Token test

on:
  push:
    branches:
      - main
      - master
  pull_request:
  schedule:
    - cron: "0 0 * * 0"
defaults:
  run:
    shell: bash
env:
  PUB_ENVIRONMENT: bot.github

jobs:
  token-test:
    # This test creates a id-token, not for talking to an external service, but
    # for testing that we are able to verify and validate the token.
    permissions:
      id-token: write
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c
      - uses: dart-lang/setup-dart@fedb1266e91cf51be2fdb382869461a434b920a3
      - name: Install dependencies
        run: dart pub get
        working-directory: app
      - name: env
        run: env
      - name: Run test
        run: dart test -P presubmit test/service/openid/github_actions_id_token_test.dart
        working-directory: app
