name: Token test

on:
  push:
    branches:
      - main
      - master
  pull_request:
  schedule:
    - cron: "0 0 * * 0"
defaults:
  run:
    shell: bash
env:
  PUB_ENVIRONMENT: bot.github

jobs:
  token-test:
    # This test creates a id-token, not for talking to an external service, but
    # for testing that we are able to verify and validate the token.
    permissions:
      id-token: write
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8
      - uses: dart-lang/setup-dart@d6a63dab3335f427404425de0fbfed4686d93c4f
      - name: Install dependencies
        run: dart pub get
        working-directory: app
      - name: env
        run: env
      - name: Run test
        run: dart test -P presubmit test/service/openid/github_actions_id_token_test.dart
        working-directory: app
