name: Dart CI
on:
  schedule:
    - cron: "0 0 * * 0" # runs on every Sunday
defaults:
  run:
    shell: bash
env:
  PUB_ENVIRONMENT: bot.github
permissions: read-all

jobs:
  weekly-tests:
    # These tests are run as a sanity-check, usually involving external data or systems.
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8
      - uses: dart-lang/setup-dart@6a218f2413a3e78e9087f638a238f6b40893203d
      - name: Install dependencies
        run: dart pub get
        working-directory: app
      - name: Run test
        run: dart test -P sanity
        working-directory: app
