name: Dart CI
on:
  schedule:
    - cron: "0 0 * * 0" # runs on every Sunday
defaults:
  run:
    shell: bash
env:
  PUB_ENVIRONMENT: bot.github
permissions: read-all

jobs:
  weekly-tests:
    # These tests are run as a sanity-check, usually involving external data or systems.
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8
      - uses: dart-lang/setup-dart@d6a63dab3335f427404425de0fbfed4686d93c4f
      - name: Install dependencies
        run: dart pub get
        working-directory: app
      - name: Run test
        run: dart test -P sanity -t sanity
        working-directory: app
