name: pub_dartdoc_data
description: Data structure for the pub-data.json
publish_to: none
environment:
  sdk: '^3.0.0'

dependencies:
  json_annotation: ^4.3.0
  sanitize_html: ^2.0.0
  html: ^0.15.0
  
dev_dependencies:
  build_runner: '^2.0.0'
  build_verify: ^3.0.0
  coverage: any # test already depends on it
  json_serializable: ^6.0.1
  source_gen: '^1.0.0'
  test: '^1.16.5'
